
package jaxws.smsc.subscriber;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SubscriberWSIPort", targetNamespace = "http://wsi.mc.nuevatel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberWSIPort {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddBalance")
    @ResponseWrapper(localName = "addBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddBalanceResponse")
    public BalanceMapPort addBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BalanceMapPort arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addHoldBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddHoldBalance")
    @ResponseWrapper(localName = "addHoldBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddHoldBalanceResponse")
    public String addHoldBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BalanceMapPort arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applyHoldBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ApplyHoldBalance")
    @ResponseWrapper(localName = "applyHoldBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ApplyHoldBalanceResponse")
    public BalanceMapPort applyHoldBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "extendHoldBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ExtendHoldBalance")
    @ResponseWrapper(localName = "extendHoldBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ExtendHoldBalanceResponse")
    public void extendHoldBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeHoldBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.RemoveHoldBalance")
    @ResponseWrapper(localName = "removeHoldBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.RemoveHoldBalanceResponse")
    public void removeHoldBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtractBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.SubtractBalance")
    @ResponseWrapper(localName = "subtractBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.SubtractBalanceResponse")
    public BalanceMapPort subtractBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<ChargePort> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addHoldCharge", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddHoldCharge")
    @ResponseWrapper(localName = "addHoldChargeResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddHoldChargeResponse")
    public String addHoldCharge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<ChargePort> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applyHoldCharge", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ApplyHoldCharge")
    @ResponseWrapper(localName = "applyHoldChargeResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ApplyHoldChargeResponse")
    public BalanceMapPort applyHoldCharge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "extendHoldCharge", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ExtendHoldCharge")
    @ResponseWrapper(localName = "extendHoldChargeResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.ExtendHoldChargeResponse")
    public void extendHoldCharge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeHoldCharge", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.RemoveHoldCharge")
    @ResponseWrapper(localName = "removeHoldChargeResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.RemoveHoldChargeResponse")
    public void removeHoldCharge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBalance", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteBalance")
    @ResponseWrapper(localName = "deleteBalanceResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteBalanceResponse")
    public BalanceMapPort deleteBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addSubscriber", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddSubscriber")
    @ResponseWrapper(localName = "addSubscriberResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddSubscriberResponse")
    public void addSubscriber(
        @WebParam(name = "arg0", targetNamespace = "")
        SubscriberPort arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.SubscriberPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubscriberPort", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.GetSubscriberPort")
    @ResponseWrapper(localName = "getSubscriberPortResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.GetSubscriberPortResponse")
    public SubscriberPort getSubscriberPort(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriber", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.UpdateSubscriber")
    @ResponseWrapper(localName = "updateSubscriberResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.UpdateSubscriberResponse")
    public void updateSubscriber(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        SubscriberPort arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSubscriber", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteSubscriber")
    @ResponseWrapper(localName = "deleteSubscriberResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteSubscriberResponse")
    public void deleteSubscriber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addSubscriberFriend", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddSubscriberFriend")
    @ResponseWrapper(localName = "addSubscriberFriendResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.AddSubscriberFriendResponse")
    public void addSubscriberFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        FriendPort arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<jaxws.smsc.subscriber.FriendPort>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubscriberFriendPortSet", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.GetSubscriberFriendPortSet")
    @ResponseWrapper(localName = "getSubscriberFriendPortSetResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.GetSubscriberFriendPortSetResponse")
    public List<FriendPort> getSubscriberFriendPortSet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSubscriberFriend", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteSubscriberFriend")
    @ResponseWrapper(localName = "deleteSubscriberFriendResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteSubscriberFriendResponse")
    public void deleteSubscriberFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        FriendPort arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns jaxws.smsc.subscriber.BalanceMapPort
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBalanceSet", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteBalanceSet")
    @ResponseWrapper(localName = "deleteBalanceSetResponse", targetNamespace = "http://wsi.mc.nuevatel.com/", className = "jaxws.smsc.subscriber.DeleteBalanceSetResponse")
    public BalanceMapPort deleteBalanceSet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

}
