
package jaxws.smsc.subscriber;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubscriberWSI", targetNamespace = "http://wsi.mc.nuevatel.com/", wsdlLocation = "file:/Users/asalazar/dev/svn/com/nuevatel/smsc.cli/trunk/core/webapp/WEB-INF/wsdl/wsi_subscriber.wsdl")
public class SubscriberWSI
    extends Service
{

    private final static URL SUBSCRIBERWSI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jaxws.smsc.subscriber.SubscriberWSI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jaxws.smsc.subscriber.SubscriberWSI.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/asalazar/dev/svn/com/nuevatel/smsc.cli/trunk/core/webapp/WEB-INF/wsdl/wsi_subscriber.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/asalazar/dev/svn/com/nuevatel/smsc.cli/trunk/core/webapp/WEB-INF/wsdl/wsi_subscriber.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUBSCRIBERWSI_WSDL_LOCATION = url;
    }

    public SubscriberWSI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberWSI() {
        super(SUBSCRIBERWSI_WSDL_LOCATION, new QName("http://wsi.mc.nuevatel.com/", "SubscriberWSI"));
    }

    /**
     * 
     * @return
     *     returns SubscriberWSIPort
     */
    @WebEndpoint(name = "SubscriberWSIPort")
    public SubscriberWSIPort getSubscriberWSIPort() {
        return super.getPort(new QName("http://wsi.mc.nuevatel.com/", "SubscriberWSIPort"), SubscriberWSIPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberWSIPort
     */
    @WebEndpoint(name = "SubscriberWSIPort")
    public SubscriberWSIPort getSubscriberWSIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsi.mc.nuevatel.com/", "SubscriberWSIPort"), SubscriberWSIPort.class, features);
    }

}
